### Controller  : SubredditController
### Method      : create
### Description : crea un nuevo subReddit
POST http://localhost:8080/api/subreddit
Content-Type: application/json

< ./request/SubReddit.json

###

### Controller  : SubredditController
### Method      : getAllSubreddits
### Description : obtiene todos los subReddits
GET http://localhost:8080/api/subreddit

###